### PR TITLE
feat(core): http route builder

### PR DESCRIPTION
**Pull request by JozefFlakus**
## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the new behavior?
Introducing the new, **EXPERIMENTAL** and more functional way of building HTTP effect routes:

**The old way of using EffectFactory:**
```typescript
const postUser$ = EffectFactory
  .matchPath('/user')
  .matchType('POST')
  .use(req$ => req$.pipe(
     // ...
  ));
```
**The new way:**
```typescript
const postUser$ = r.pipe(
  r.matchPath('/user'),
  r.matchType('POST'),
  r.useEffect(req$ => req$.pipe(
     // ...
  )));
```

**What does it give us?**
- Consistent API (see RxJS stream pipe)
- HTTP route definition with functional flavor 👉 avoids OOP builder pattern
- Open API for the future
- We can apply additional metadata using `r.applyMeta` function
- Opens the possibility for using `|>` operator when the [TC39 proposal](https://github.com/tc39/proposal-pipeline-operator) will reach the desired stage

```typescript
const postUser$ = r.pipe(
  r.matchPath('/user'),
  r.matchType('POST'),
  r.use(m_1$),
  r.use(m_2$),
  r.use(m_3$),
  r.useEffect(req$ => req$.pipe(
     // ...
  )),
  r.applyMeta({ data: 'some meta here' }),
);
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other
Since version 2.0 both APIs will be valid. It will be up to the developer which way he will choose.
We will see where the new API will bring us and what future possibilities it will open.

Besides the main feature, the PR includes `fp-ts` library as a core dependency. I see it's more usefullness in the near future.

### CODE REVIEW

**Comment by mistyharsh** [comment]
This looks great. I am looking at the pipe implementation. The type definition is:

```typescript
type Pipeable = (route: Either<CoreError, Partial<RouteEffect>>) => Either<CoreError, Partial<RouteEffect>>;
```

It looks like it won't prevent users from doing this:

```typescript
const postUser$ = r.pipe(
  r.matchPath('/user'),
  r.matchType('POST'),
  r.use(m_1$),
  r.matchType('POST'),   // PROBLEM
  r.use(m_2$),
  r.useEffect(req$ => req$.pipe(
     // ...
  )));
```

**Comment by JozefFlakus** [comment]
Hi @mistyharsh,

The problem with `pipe` implementation is that we can't really know which "operator" will be applied first on which position, without introducing indexed monads for hamburger-like building, which is also a limitation from TypeScript side.

The possibilities that I can see for now:
1. to define a limited set of possible operators placement, eg. PathOperator -> TypeOperator -> MiddlewareOperator -> ... -> EffectOperator

or

2. to allow passing an infinite number operators (it will remain the same)

or

3. to experiment with `fp-ts` IxMonad, but I'm not sure if it will be possible to achieve the desired effect without too many boilerplate code

**Comment by JozefFlakus** [comment]
@mistyharsh Yesterday I was playing with indexed monad and it turned out that it can be perfectly applied to this set of problems. I was able to preserve etexactly the same `pipe` API.

The only drawback is that we have to limit the maximum number of operators applied to the `pipe` chain in order to have the prover type inference across the IxMonad.

```typescript
const postUser$ = r.pipe(
  r.matchPath('/user'),
  r.matchType('POST'),
  r.use(m_1$),
  r.matchType('POST'),   // the compiler will warn here 🙂 
  r.use(m_2$),
  r.useEffect(req$ => req$.pipe(
     // ...
  )));
```

BTW. this kind of problem solving deserves in the future for some medium article I think. 🤔

**Comment by mistyharsh** [comment]
Yes. That looks great. I was looking at Ramda `compose` implementation for this issue. Essentially, this compiles very well:

```javascript
const postUser$ = r.useEffect(
    r.use(m_2$)(
        r.use(m_1$)(
            r.matchType('POST')(
                r.matchPath('/user')
            )
        )
    ),
    req$ => req$.pipe(/* ... */)
);
```
Its similar representation with compose compiles perfectly with TypeScript. The implementation here resembles the one in Ramda. I think it should be fine to limit pipe/compose to 9-10 operators. The safety provided by this still outweights the benefit of infinite pipeline as we hardly write code that big.

And if it needs to be split we can always go back to nested `switchMap`. But again, going beyond 10 would probably count as antipattern.

**Pull request merged**
