### PR TITLE
feat(middleware-io): `validateEvent` + API deprecations

### PR DESCRIPTION
**Pull request by JozefFlakus**
## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the new behavior?
- **@marblejs/middleware-io** - `validateRequest` + `validateEvent` - new validator entrypoints
- **@marblejs/middleware-io** - `validateEvent` can take single event object instead of `Observable<Event>`
- **@marblejs/middleware-io** - deprecated `requestValidator$` and `eventValidator$`

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by JozefFlakus** [comment]
@tstelzer Do you think that this change is a breaking that should be introduced in the v4 release...? 🤔

**Comment by tstelzer** [comment]
> @tstelzer Do you think that this change is enough breaking the current API? Should it be introduced in the v4 release...? thinking

I wonder if there is a way without making it a breaking change? Making it context-aware, so it can be used backwards compatible? Or export it with a different name, just deprecating the old one?

**Comment by JozefFlakus** [comment]
> Making it context-aware, so it can be used backwards compatible?
Right now I don't have any idea how we can accomplish it this way since it acts as a normal function 🤔 

> Or export it with a different name, just deprecating the old one?
It could be easier but I'm thinking about the naming. Do you have any suggestions?

**Comment by tstelzer** [comment]
How about `validateEvent` or just `validate`? Fits the style of imperative verbs, e.g. `use`, `delay`, etc.

**Comment by JozefFlakus** [comment]
> How about `validateEvent` or just `validate`? Fits the style of imperative verbs, e.g. `use`, `delay`, etc.

`validateEvent` seems to be more descriptive since the middleware is only responsible for processing Events. There is a separate middleware for HTTP requests.

**Comment by tstelzer** [comment]
Sure, I am just thinking if we would do the same change to the HTTP middleware, both would have the signature `validate :: codec -> event$`, right?

**Comment by JozefFlakus** [comment]
> both would have the signature `validate :: codec -> event$`, right?

Correct:
HTTP:
```hs
validateRequest :: codec -> req$
```

Event:
```hs
validateEvent :: codec -> event$
```

But combining it into one generalized middleware could be frustrating.

**Comment by tstelzer** [comment]
Nah, didn't mean to imply to export _one_ middleware `validate`, rather export `validate` from both modules, each with its own signature. But I don't mind `validateRequest` and `validateEvent`, its just an aesthetics thing. Same thing, really.

**Comment by JozefFlakus** [comment]
TBH I'm not a big fan of the current middleware naming so I'm really open to change it and deprecate the old ones :)

**Comment by JozefFlakus** [comment]
BTW. since I looked again at all middlewares that we can apply to req/event streams, it turned out that `use` operator is no needed anymore. The `use` operator was necessary in pre 3 release when the `HttpEffect` was separated into `req$`, `res` and the third effect context parameter.

**Comment by JozefFlakus** [comment]
@tstelzer after implementing it via this way I'm not sure if this is a good behavior... 
The function declaration says:

```typescript
validateEvent = (schema: Schema) => (event$: Observable<Event>) => Observable<ValidatedEvent>
```

But in reality it can result in another event (validation error event) type which differs from the origin one...
The solution would be to use `Either` type but this API does not glue well with `Observable` type.

The thing is that with proposed solution this API is 100% valid. But will result with an error since the event in `map` operator will be the same if the validation will fail...
```
      event$.pipe(
        matchEvent('FOO'),
        validateEvent(t.number),
        map(event => ({ ...event, type: 'FOO_RESULT', payload: event.payload + 1 })),
      );
```

**Comment by tstelzer** [comment]
Oh, I agree that it should throw in case of validation. Until there is a solid `ObservableEither`, I don't think we get around throwing for top-level control-flow.

**Pull request closed without merging**
